In [66]:
import pandas as pd
import datetime

Cleaning Feb-2021 to Jun-2021:
* Load csv
* Drop duplicates and NA
* Change start and stop times to datetime
* Add tripduration column
* Rename columns to match previous spreadsheets
* Add season column
* Order columns

In [110]:
Jun2021 = pd.read_csv('JC-202106-citibike-tripdata.csv')
df = pd.DataFrame(Jun2021)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['ended_at'] = pd.to_datetime(df['ended_at'])
df['started_at'] = pd.to_datetime(df['started_at'])
df["tripduration"] = df["ended_at"] - df["started_at"]
df = df.rename(columns={"member_casual": "usertype", "started_at": "starttime", "ended_at": "stoptime"})
df["season"] = "Summer"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "rideable_type", "ride_id"]
Jun2021 = df.reindex(columns=column_names)

In [111]:
May2021 = pd.read_csv('JC-202105-citibike-tripdata.csv')
df = pd.DataFrame(May2021)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['ended_at'] = pd.to_datetime(df['ended_at'])
df['started_at'] = pd.to_datetime(df['started_at'])
df["tripduration"] = df["ended_at"] - df["started_at"]
df = df.rename(columns={"member_casual": "usertype", "started_at": "starttime", "ended_at": "stoptime"})
df["season"] = "Spring"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "rideable_type", "ride_id"]
May2021 = df.reindex(columns=column_names)

In [112]:
Apr2021 = pd.read_csv('JC-202104-citibike-tripdata.csv')
df = pd.DataFrame(Apr2021)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['ended_at'] = pd.to_datetime(df['ended_at'])
df['started_at'] = pd.to_datetime(df['started_at'])
df["tripduration"] = df["ended_at"] - df["started_at"]
df = df.rename(columns={"member_casual": "usertype", "started_at": "starttime", "ended_at": "stoptime"})
df["season"] = "Spring"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "rideable_type", "ride_id"]
Apr2021 = df.reindex(columns=column_names)

In [113]:
Mar2021 = pd.read_csv('JC-202103-citibike-tripdata.csv')
df = pd.DataFrame(Mar2021)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['ended_at'] = pd.to_datetime(df['ended_at'])
df['started_at'] = pd.to_datetime(df['started_at'])
df["tripduration"] = df["ended_at"] - df["started_at"]
df = df.rename(columns={"member_casual": "usertype", "started_at": "starttime", "ended_at": "stoptime"})
df["season"] = "Spring"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "rideable_type", "ride_id"]
Mar2021 = df.reindex(columns=column_names)

In [114]:
Feb2021 = pd.read_csv('JC-202102-citibike-tripdata.csv')
df = pd.DataFrame(Feb2021)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['ended_at'] = pd.to_datetime(df['ended_at'])
df['started_at'] = pd.to_datetime(df['started_at'])
df["tripduration"] = df["ended_at"] - df["started_at"]
df = df.rename(columns={"member_casual": "usertype", "started_at": "starttime", "ended_at": "stoptime"})
df["season"] = "Winter"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "rideable_type", "ride_id"]
Feb2021 = df.reindex(columns=column_names)

Cleaning Data June-2020 to Jan-2021
* Load csv
* Drop duplicates and NA
* Change start and stop times to datetime
* Drop and readd tripduration column
* Rename subscribers to match previous spreadsheets
* Add season column
* Order columns

In [115]:
Jan2021 = pd.read_csv('JC-202101-citibike-tripdata.csv')
df = pd.DataFrame(Jan2021)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['stoptime'] = pd.to_datetime(df['stoptime'])
df['starttime'] = pd.to_datetime(df['starttime'])
df['usertype'] = df['usertype'].replace({'Subscriber': 'member', 'Customer': 'casual'})
df.drop(columns=['tripduration'])
df["tripduration"] = df["stoptime"] - df["starttime"]
df["season"] = "Winter"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "bikeid", "birthyear", "gender"]
Jan2021 = df.reindex(columns=column_names)

In [116]:
Dec2020 = pd.read_csv('JC-202012-citibike-tripdata.csv')
df = pd.DataFrame(Dec2020)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['stoptime'] = pd.to_datetime(df['stoptime'])
df['starttime'] = pd.to_datetime(df['starttime'])
df['usertype'] = df['usertype'].replace({'Subscriber': 'member', 'Customer': 'casual'})
df.drop(columns=['tripduration'])
df["tripduration"] = df["stoptime"] - df["starttime"]
df["season"] = "Winter"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "bikeid", "birthyear", "gender"]
Dec2020 = df.reindex(columns=column_names)

In [117]:
Nov2020 = pd.read_csv('JC-202011-citibike-tripdata.csv')
df = pd.DataFrame(Nov2020)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['stoptime'] = pd.to_datetime(df['stoptime'])
df['starttime'] = pd.to_datetime(df['starttime'])
df['usertype'] = df['usertype'].replace({'Subscriber': 'member', 'Customer': 'casual'})
df.drop(columns=['tripduration'])
df["tripduration"] = df["stoptime"] - df["starttime"]
df["season"] = "Fall"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "bikeid", "birthyear", "gender"]
Nov2020 = df.reindex(columns=column_names)

In [118]:
Oct2020 = pd.read_csv('JC-202010-citibike-tripdata.csv')
df = pd.DataFrame(Oct2020)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['stoptime'] = pd.to_datetime(df['stoptime'])
df['starttime'] = pd.to_datetime(df['starttime'])
df['usertype'] = df['usertype'].replace({'Subscriber': 'member', 'Customer': 'casual'})
df.drop(columns=['tripduration'])
df["tripduration"] = df["stoptime"] - df["starttime"]
df["season"] = "Fall"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "bikeid", "birthyear", "gender"]
Oct2020 = df.reindex(columns=column_names)

In [119]:
Sep2020 = pd.read_csv('JC-202009-citibike-tripdata.csv')
df = pd.DataFrame(Sep2020)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['stoptime'] = pd.to_datetime(df['stoptime'])
df['starttime'] = pd.to_datetime(df['starttime'])
df['usertype'] = df['usertype'].replace({'Subscriber': 'member', 'Customer': 'casual'})
df.drop(columns=['tripduration'])
df["tripduration"] = df["stoptime"] - df["starttime"]
df["season"] = "Fall"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "bikeid", "birthyear", "gender"]
Sep2020 = df.reindex(columns=column_names)

In [120]:
Aug2020 = pd.read_csv('JC-202008-citibike-tripdata.csv')
df = pd.DataFrame(Aug2020)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['stoptime'] = pd.to_datetime(df['stoptime'])
df['starttime'] = pd.to_datetime(df['starttime'])
df['usertype'] = df['usertype'].replace({'Subscriber': 'member', 'Customer': 'casual'})
df.drop(columns=['tripduration'])
df["tripduration"] = df["stoptime"] - df["starttime"]
df["season"] = "Summer"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "bikeid", "birthyear", "gender"]
Aug2020 = df.reindex(columns=column_names)

In [121]:
Jul2020 = pd.read_csv('JC-202007-citibike-tripdata.csv')
df = pd.DataFrame(Jul2020)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['stoptime'] = pd.to_datetime(df['stoptime'])
df['starttime'] = pd.to_datetime(df['starttime'])
df['usertype'] = df['usertype'].replace({'Subscriber': 'member', 'Customer': 'casual'})
df.drop(columns=['tripduration'])
df["tripduration"] = df["stoptime"] - df["starttime"]
df["season"] = "Summer"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "bikeid", "birthyear", "gender"]
Jul2020 = df.reindex(columns=column_names)

In [122]:
Jun2020 = pd.read_csv('JC-202006-citibike-tripdata.csv')
df = pd.DataFrame(Jun2020)
df = df.drop_duplicates()
df = df.dropna(how='any')
df['stoptime'] = pd.to_datetime(df['stoptime'])
df['starttime'] = pd.to_datetime(df['starttime'])
df['usertype'] = df['usertype'].replace({'Subscriber': 'member', 'Customer': 'casual'})
df.drop(columns=['tripduration'])
df["tripduration"] = df["stoptime"] - df["starttime"]
df["season"] = "Summer"
column_names = ["season", "starttime", "stoptime", "tripduration", "start_station_name", "start_station_id", "start_lat", "start_lng", "end_station_name",
                "end_station_id", "end_lat", "end_lng", "usertype", "bikeid", "birthyear", "gender"]
Jun2020 = df.reindex(columns=column_names)

# Merging Spreadsheets together

In [125]:
months = [Jun2020, Jul2020, Aug2020, Sep2020, Nov2020, Dec2020, Jan2021, Feb2021, Mar2021, Apr2021, May2021, Jun2021]
cleanData = pd.concat(months)
cleanData.head()

,season,starttime,stoptime,tripduration,start_station_name,start_station_id,start_lat,start_lng,end_station_name,end_station_id,end_lat,end_lng,usertype,bikeid,birthyear,gender,rideable_type,ride_id
0,Summer,2020-06-01 00:02:21.750,2020-06-01 00:04:24.325,00:02:02.575000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,member,42489.0,NaN,1.0,NaN,NaN
1,Summer,2020-06-01 00:12:27.109,2020-06-01 00:33:50.054,00:21:22.945000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,member,42183.0,NaN,1.0,NaN,NaN
2,Summer,2020-06-01 01:19:59.209,2020-06-01 01:23:05.893,00:03:06.684000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,member,42140.0,NaN,1.0,NaN,NaN
3,Summer,2020-06-01 01:26:42.205,2020-06-01 01:28:53.804,00:02:11.599000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,member,42120.0,NaN,1.0,NaN,NaN
4,Summer,2020-06-01 01:27:33.709,2020-06-01 01:32:00.189,00:04:26.480000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,member,42437.0,NaN,2.0,NaN,NaN